# 2. NumPy

In [1]:
a = [1, 2, 3]
a

[1, 2, 3]

In [2]:
[a+10 for a in a]

[11, 12, 13]

In [3]:
[10, 3.14, 'Park', [1, 2, 3]]

[10, 3.14, 'Park', [1, 2, 3]]

In [4]:
# NumPy 라이브러리 설치
#!pip install numpy

In [5]:
# NumPy 라이브러리 불러오기
import numpy as np

In [6]:
# 넘파이 배열 생성1 : 리스트 사용
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [7]:
arr1 + 10

array([11, 12, 13, 14])

In [8]:
# 넘파이 배열 생성2
arr2 = np.array([1, 2, 'Park'])
print(arr2)

['1' '2' 'Park']


In [9]:
# 넘파이 배열 생성3 : 2차원 배열
arr3 = np.array([[1, 2, 3], [11, 12, 13]])
print(arr3)

[[ 1  2  3]
 [11 12 13]]


In [10]:
# 속성1 : 배열의 차원
arr3.ndim

2

In [11]:
# 속성2 : 배열 요소의 자료형
arr3.dtype

dtype('int64')

In [12]:
arr3.itemsize

8

In [13]:
arr3.shape

(2, 3)

In [14]:
arr1.shape

(4,)

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(20, 50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [19]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [20]:
# 넘파이 배열 인덱싱 : 정수 사용
arr8 = np.arange(10, 51, 10)
print(arr8)
print(arr8[1])        # 20
print(arr8[-2])       # 40

[10 20 30 40 50]
20
40


In [21]:
# 넘파이 배열 인덱싱 : 배열 사용
idx = [0, 1, 4]
print(arr8[idx])

[10 20 50]


In [22]:
# 넘파일 배열 인덱싱 : 논리값(True, False) 사용
mask = arr8 > 25
print(arr8[mask])

[30 40 50]


In [23]:
# 넘파이 배열 슬라이싱
arr9 = np.arange(11, 16)
arr9

array([11, 12, 13, 14, 15])

In [24]:
# 1번 인덱스부터 4번 인덱스 전까지
arr9[1:4]

array([12, 13, 14])

In [25]:
arr9[:3]

array([11, 12, 13])

In [26]:
arr9[3:]

array([14, 15])

In [27]:
arr9[::2]

array([11, 13, 15])

In [28]:
# 역순 정렬
arr9[::-1]

array([15, 14, 13, 12, 11])

In [29]:
arr9 - 10

array([1, 2, 3, 4, 5])

In [30]:
arr9 <= 13

array([ True,  True,  True, False, False])

In [31]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
x + y

array([11, 22, 33])

In [32]:
# 얕은 복사
arr11 = np.arange(6)
copy11 = arr11

print(arr11)
print(copy11)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [33]:
# 복사본을 수정 -> 원본도 변함
copy11[0] = 10

print(arr11)
print(copy11)

[10  1  2  3  4  5]
[10  1  2  3  4  5]


In [34]:
# 원본을 수정 -> 복사본도 변함
arr11[-1] = -5

print(arr11)
print(copy11)

[10  1  2  3  4 -5]
[10  1  2  3  4 -5]


In [35]:
# 깊은 복사
arr12 = np.arange(11, 16)
copy12 = arr12.copy()

print(arr12)
print(copy12)

[11 12 13 14 15]
[11 12 13 14 15]


In [36]:
# 복사본을 바꿔도 -> 원본은 변하지 않음
copy12[0] = 0

print(arr12)
print(copy12)

[11 12 13 14 15]
[ 0 12 13 14 15]


In [37]:
# 원본을 바꿔도 -> 복사본은 변하지 않음
arr12[-1] = 100

print(arr12)
print(copy12)

[ 11  12  13  14 100]
[ 0 12 13 14 15]
